### ISSUE TITLE
Error in initialize()

### ISSUE THREAD

**Issue by GuyKh** [Petro31/ad_people_tracker#1]
Getting this error in AppDaemon 4.0.2 - running on RaspberryPi from self built docker image from original AppDaemon:

```
2020-02-10 14:01:11.322339 WARNING events: ------------------------------------------------------------
2020-02-10 14:01:11.323433 WARNING events: Unexpected error running initialize() for events
2020-02-10 14:01:11.324235 WARNING events: ------------------------------------------------------------
2020-02-10 14:01:11.345404 WARNING events: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/appdaemon/app_management.py", line 144, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/utils.py", line 282, in run_in_executor
    response = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/conf/apps/people_tracker/people_tracker.py", line 63, in initialize
    self.log(self.get_state(self.guest_entity_id, attribute='all'), level = self._level)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/utils.py", line 195, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/appdaemon/utils.py", line 291, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/appdaemon/adapi.py", line 1344, in get_state
    return await self.AD.state.get_state(self.name, namespace, entity_id, attribute, default, copy, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/state.py", line 360, in get_state
    raise ValueError("{}: Querying a specific attribute is only possible for a single entity".format(name))
ValueError: events: Querying a specific attribute is only possible for a single entity
```

**Comment by bullb0g** [comment]
I get a similar message. I have a very different setup though.
Home Assistant OS via Proxmox on an I7 NUC. 
AppDaemon4 installed as an addon. Addon version 0.1.2.

`2020-02-19 03:08:22.897984 INFO AppDaemon: Initializing app events using class PeopleTracker from module people_tracker
2020-02-19 03:08:22.914949 WARNING events: ------------------------------------------------------------
2020-02-19 03:08:22.915368 WARNING events: Unexpected error running initialize() for events
2020-02-19 03:08:22.915645 WARNING events: ------------------------------------------------------------
2020-02-19 03:08:22.918953 WARNING events: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 145, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/people_tracker/people_tracker.py", line 63, in initialize
    self.log(self.get_state(self.guest_entity_id, attribute='all'), level = self._level)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 191, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 285, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 1310, in get_state
    return await self.AD.state.get_state(
  File "/usr/lib/python3.8/site-packages/appdaemon/state.py", line 343, in get_state
    raise ValueError(
ValueError: events: Querying a specific attribute is only possible for a single entity
2020-02-19 03:08:22.920437 WARNING events: ------------------------------------------------------------`

**Comment by make-all** [comment]
The clue seems to be in this log line:
File "/conf/apps/people_tracker/people_tracker.py", line 63, in initialize
    self.log(self.get_state(self.guest_entity_id, attribute='all'), level = self._level)

In the documentation, guest_entity_id is marked as optional.  But it seems from this error that it is not, which is a shame, as I don't really have a need for tracking guests.

**Comment by harryd100** [comment]
Here too

This happens when i remove:
guest_entity_id: input_boolean.guests
from apps.yaml

2020-03-18 16:42:59.487560 WARNING events: ------------------------------------------------------------
2020-03-18 16:42:59.488520 WARNING events: Unexpected error running initialize() for events
2020-03-18 16:42:59.489255 WARNING events: ------------------------------------------------------------
2020-03-18 16:42:59.495076 WARNING events: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 145, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/people_tracker.py", line 63, in initialize
    self.log(self.get_state(self.guest_entity_id, attribute='all'), level = self._level)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 191, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 285, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 1310, in get_state
    return await self.AD.state.get_state(
  File "/usr/lib/python3.8/site-packages/appdaemon/state.py", line 343, in get_state
    raise ValueError(
ValueError: events: Querying a specific attribute is only possible for a single entity

2020-03-18 16:42:59.495947 WARNING events: ------------------------------------------------------------

**Comment by Petro31** [comment]
I apologize, I never knew these issues were created.  I'll investigate.
