### ISSUE TITLE
Showing other entities as people present

### ISSUE THREAD

**Issue by bensuffolk** [Petro31/ad_people_tracker#6]
After the latest upgrade to HASS (I'm running 2022.2.2) I started to see a lot of other entities showing as at home. I have WiFi tracking so all my light switches etc are detected. However they are all set to not track in the known_devices file.

I have the guest boolean set to false.

I looked in the logs for AppDameon and find the following errors shown:

```
2022-02-06 11:45:51.383037 WARNING people_at_home: ------------------------------------------------------------
2022-02-06 11:45:51.383515 WARNING people_at_home: Unexpected error in worker for App people_at_home:
2022-02-06 11:45:51.383971 WARNING people_at_home: Worker Ags: {'id': 'cd3df720e85b4decaa790bdeaa908c39', 'name': 'people_at_home', 'objectid': '23d23f07d82e463ab79b58e8615aa297', 'type': 'state', 'function': <bound method PeopleTracker.track_person of <people_tracker.PeopleTracker object at 0x7fa9167a0b50>>, 'attribute': 'state', 'entity': 'persistent_notification.config_entry_discovery', 'new_state': 'notifying', 'old_state': None, 'pin_app': True, 'pin_thread': 2, 'kwargs': {'entity': 'person.ben_suffolk', '__thread_id': 'thread-2'}}
2022-02-06 11:45:51.384361 WARNING people_at_home: ------------------------------------------------------------
2022-02-06 11:45:51.384724 WARNING people_at_home: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker
    funcref(
  File "/config/appdaemon/apps/ad_people_tracker/people_tracker.py", line 98, in track_person
    name = self.clean_persons_name(entity)
  File "/config/appdaemon/apps/ad_people_tracker/people_tracker.py", line 92, in clean_persons_name
    name = name.split(' ')[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by kaizersoje** [comment]
I am seeing the same issue as well. 
 
I can see in the `people` attribute of the `sensor.people_tracker` sensor that it is showing totally random stuff, with a current value of 18. JFYI - I have only defined 2 person entities.

`Amazon, Asustek, Bed, Brilliant, Cast_Devices, Espressif, Evening, Front, Google, Inside, Mymodem, Nmap, Samsung, Schedule, Soundbar, Study, Tct, Texas, Tp-Link, Universal`

I have plotted the sensor data in a chart for the last 2 days.

![image](https://user-images.githubusercontent.com/54566217/153748724-c57d64ce-7a87-4f72-b86e-cbbc486d2382.png)

**Comment by Petro31** [comment]
> I am seeing the same issue as well.
> 
> I can see in the `people` attribute of the `sensor.people_tracker` sensor that it is showing totally random stuff, with a current value of 18. JFYI - I have only defined 2 person entities.
> 
> `Amazon, Asustek, Bed, Brilliant, Cast_Devices, Espressif, Evening, Front, Google, Inside, Mymodem, Nmap, Samsung, Schedule, Soundbar, Study, Tct, Texas, Tp-Link, Universal`
> 
> I have plotted the sensor data in a chart for the last 2 days.
> 
> ![image](https://user-images.githubusercontent.com/54566217/153748724-c57d64ce-7a87-4f72-b86e-cbbc486d2382.png)

It tracks everything you provide to it.  If you're providing all those extra entities, it will track them.  Also, as stated in other issues, I no longer use this, nore can I update it as I no longer use AppDaemon.  I've replaced this with a simple template sensor.

**Comment by Petro31** [comment]
https://github.com/Petro31/ad_people_tracker/issues/4#issuecomment-1008861234
